version: '3.6'

services:
  ganache:
    container_name: ganache
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/ganache/Dockerfile
    ports:
      - 8545:8545

  truffle:
    container_name: truffle
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/production/truffle:latest
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/truffle/Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    tty: true
    volumes:
      - abis-volume:/backend/abis
    depends_on:
      - ganache

  postgres:
    image: postgres:10.6-alpine
    container_name: postgres
    env_file:
      - ../../../.env.production
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  frontend:
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/frontend/Dockerfile
      target: production
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/production/frontend:latest
    container_name: frontend
    env_file:
      - ../../../.env.production
    volumes:
      - ${PWD}/logs/production/frontend:/logs/
    depends_on:
      - postgres
      - ganache
      - truffle
    ports: 
      - 80:80

volumes:
  postgres-volume:
  abis-volume:
  prisma-volume:
  # public-volume:
